[package]
name = "font_editor"
version = "0.1.1"
edition = "2021"
description = "A font editor for rqos"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font.workspace = true
sfml.workspace = true
