[package]
name = "font_editor"
description = "A font editor for rqos"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
font.workspace = true
sfml.workspace = true
