[package]
name = "rqos"
version = "0.1.1"
authors = ["Raoul van Putten <53082972+rvputten@users.noreply.github.com>"]
edition = "2021"
description = "Operating system on top of the Linux kernel and sfml"
license = "MIT"
repository = "https://github.com/rvputten/rqos.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.21"
