[package]
name = "font"
description = "rqos library to render fonts"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sfml.workspace = true
