[package]
name = "config"
description = "rqos wide configuration settings"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
