[package]
name = "rqsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml.workspace = true
color.workspace = true
text.workspace = true
edit.workspace = true
font.workspace = true
