[package]
name = "edit"
description = "Edit field"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sfml.workspace=true
font.workspace = true
text.workspace = true
