[package]
name = "color"
description = "Handle ANSI color codes and escape sequences"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sfml.workspace = true
