[package]
name = "text"
description = "Text field"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sfml.workspace = true
font.workspace = true
color.workspace = true
